engines:
  eslint:
    enabled: true
    channel: eslint-4
  isort:
    enabled: true
    channel: beta
  pep8:
    enabled: true
  pylint:
    enabled: true
    channel: beta
    checks:
      import-error:
        enabled: false
  duplication:
    enabled: true
    config:
      languages:
        python:
          mass_threshold: 100
          python_version: 3
exclude_patterns:
- ".*"
- "migrations/"
- "tests/"
- "**/test_*"
- "webpack.config.js"
ratings:
  paths:
  - texrrow/**
